### ISSUE TITLE
Sorry, you are not allowed to access this page.

### ISSUE THREAD

**Issue by medber** [albertosgz/Wordpress_BigBlueButton_plugin#20]
Installed the new BBB 3 Beta-Plugin on my WP 5.3.1 Site. After activating the plugin if I press "ROOMS" in the config Panel the system rejects by saying

**"Sorry, you are not allowed to access this page."**

I can´t continue configuration the Plugin.

Plugin is activated, user has Adminstrator rights.
Shouldn´t be like this, or am I missing something here?

**Comment by medber** [comment]
Seems like an issue with iThemes Security which I use on site - as many many many other WP Admins.

[](https://wordpress.org/support/topic/old-rooms-gone-after-updating/)

**Comment by albertosgz** [comment]
Thank you for the clue!
