### ISSUE TITLE
List of Active Meeting Rooms Not listing

### ISSUE THREAD

**Issue by GiorgioBart** [albertosgz/Wordpress_BigBlueButton_plugin#22]
The list of active rooms does not show anything either in the administration panel or by using the short code on a page.

BBB version 2.2.9 
WordPress 5.4

**Comment by albertosgz** [comment]
Did you check BBB settings and try to enter into a room? In all our installations the list run like a charm.

**Comment by GiorgioBart** [comment]
Hi, yes, I can correctly define and start a room. 
I have to add the info that the plugin points to the scalelite load balancer. But this shouldn't be a problem because with "bigbluebutton-API-Buddy" I can list the meetings using the getMeetings API.

Also, but I will open a separate issue, I have a 1004 error problem defining a room with registration.

Thanks for this wonderful plugin!

**Comment by albertosgz** [comment]
did you try to point directly to the BBB server to check out if plugin is
working properly?

**Comment by GiorgioBart** [comment]
I just tried to point it directly to the BBB node. The behavior is the same: If there are no active meetings, in the administration panel I have the text "Unable to display the meetings". If a meeting is active, the text disappears but in the active meeting table I have "no data available in table". I attach two screenshots
![Schermata del 2020-05-13 15-46-06](https://user-images.githubusercontent.com/23031295/81821541-3cd95180-9532-11ea-8d28-087323f23c3a.png)
![Schermata del 2020-05-13 15-46-48](https://user-images.githubusercontent.com/23031295/81821543-3e0a7e80-9532-11ea-9488-9a8b4ac3dd5f.png)

**Comment by albertosgz** [comment]
Can you post here a trace with between plugin and BBB server? just to
checkout if some unexpected field is receiving

**Comment by albertosgz** [comment]
Can you post here the text? It helps me to trace the error.
The plugin may not parsing properly the ajax response.

**Comment by GiorgioBart** [comment]
`{
	"meeting": {
		"returncode": "SUCCESS",
		"meetingName": "test01",
		"meetingID": "xxxxxxx",
		"internalMeetingID": "xxxxxx",
		"createTime": "1589378581373",
		"createDate": "Wed May 13 16:03:01 CEST 2020",
		"voiceBridge": "xxx",
		"dialNumber": "xxx",
		"attendeePW": "xxx",
		"moderatorPW": "xxx",
		"running": "true",
		"duration": "0",
		"hasUserJoined": "true",
		"recording": "false",
		"hasBeenForciblyEnded": "false",
		"startTime": "1589378581407",
		"endTime": "0",
		"participantCount": "1",
		"listenerCount": "0",
		"voiceParticipantCount": "1",
		"videoCount": "0",
		"maxUsers": "0",
		"moderatorCount": "1",
		"attendees": {
			"attendee": {
				"userID": "w_jd7lrkz688fq",
				"fullName": "admin",
				"role": "MODERATOR",
				"isPresenter": "true",
				"isListeningOnly": "false",
				"hasJoinedVoice": "true",
				"hasVideo": "false",
				"clientType": "HTML5"
			}
		},
		"metadata": {
			"originservercommonname": "xxx",
			"origin": "WordPress",
			"originurl": "https://xxxxxx/wp-admin/options-general.php?page=bigbluebutton_general",
			"origintag": "wp_plugin-bbb_admin_panel_ 1.1.11",
			"originversion": "5.4",
			"originservername": "https://xxxxxx"
		},
		"isBreakout": "false"
	}
}`

**Comment by GiorgioBart** [comment]
I get it! works if the number of active meetings is> 1

**Comment by albertosgz** [comment]
It sounds like a bug :(
I will dig it.
Grazie Giorgio!

**Comment by GiorgioBart** [comment]
Thank  to you for this plugin!
