### ISSUE TITLE
Voicebridge MUST be >= 5 digit

### ISSUE THREAD

**Issue by GiorgioBart** [albertosgz/Wordpress_BigBlueButton_plugin#23]
the voicebridge MUST be a number consisting of at least 5 digits. Otherwise, the error (generic 1004 error) in the figure may occur and you may not be able to use the microphone.

![error](https://user-images.githubusercontent.com/23031295/81839274-9d26be00-9547-11ea-814b-6757f3fe9c20.png)

**Comment by albertosgz** [comment]
I'm sorry, I don't understand de issue. You mean the admin panel must consider 5 digits at least to set up the voicebridge, no less?

**Comment by GiorgioBart** [comment]
Yes. If I insert a voice bridge smaller than 5 digits the error shown in the figure is raised

**Comment by albertosgz** [comment]
Thank you Giorgio.

I will check it out.
