### ISSUE TITLE
BBB Panel permission issues

### ISSUE THREAD

**Issue by FilipeOS** [albertosgz/Wordpress_BigBlueButton_plugin#24]
Hi,

I'm having issues on our site.

We have a membership plugin that create a role for each membership level. After this we go to BBB Panel and change the permissions for the user roles but it's not working properly.

We used to have the plugin from BBB (blindside) that showed like your Panel but on BBB v2.2 we had to add your plugin since blindside was it's too freaking basic (and bad).

A room is created on "Rooms" and then with your plugin we changed the permissions. For some reason we cannot have it both enabled anymore because your plugin it's not forcing the permissions and when we click on "Join" it shows WP error screen saying to ask permissions and try again...

Any advise?

**Comment by albertosgz** [comment]
Do you need both?
I cannot say anything since I don't test both plugins at the same time.

**Comment by FilipeOS** [comment]
When I try to deactivate the official BBB plugin and set the token from BBB Panel it's says room it's not properly setup (since it worked before).

Before we find your plugin we added all Rooms on bbb plugin (from blindside), this is why we use both

**Comment by albertosgz** [comment]
Maybe after deactivate the official BBB plugin, the tables have been
cleaned. That's why it says the room is not properly setup. Can you check
it out in db?

**Comment by FilipeOS** [comment]
Hi there,

I deactivated the blindside plugin, replaced the token and for some miracle it's not saying it's wrong configurated (crazy like always)

PS: Why it's not possible to change a room without deleting and creating a new one?

Thank you!

**Comment by albertosgz** [comment]
The table is not editable. I need to change it in order to be able to change it. It requires a major change. If it is important to you, please open a new issue as a new feature.
