### ISSUE TITLE
This plugin is giving a 504 error

### ISSUE THREAD

**Issue by s1-ranjan** [albertosgz/Wordpress_BigBlueButton_plugin#27]
After configuring room with this plugin it throws 504 error

**Comment by albertosgz** [comment]
Can you give me more information? Like BBB version, aure using balancers, etc?

**Comment by s1-ranjan** [comment]
I was using with the FREE BigBlueButton server provided by Blindside Networks, so it's difficult for me to provide you those details.

**Comment by albertosgz** [comment]
With the Free BBB configuration, the plugin is not working properly, since it hangs up due to internal timeouts. I try to fix, but it requires a big re-development, that I can't afford at the moment.
With other BBB server it should work.
