### ISSUE TITLE
tables not displayed on the admin backend of the module

### ISSUE THREAD

**Issue by danionescu2007** [albertosgz/Wordpress_BigBlueButton_plugin#28]
![image](https://user-images.githubusercontent.com/4688610/89704515-f2167c80-d95c-11ea-8c90-d98815a26b2a.png)

All I get in browser dev console is:
> [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (pdfmake.min.js.map, line 0)
![image](https://user-images.githubusercontent.com/4688610/89704537-2853fc00-d95d-11ea-85e9-ed602a942208.png)

I tried the version in wordpress repository (installer) and also I downloaded the zip and installed it manually. It's all the same result.

Any idea for a quick fix?
I can give you the admin user to test directly
Thank you!

**Comment by albertosgz** [comment]
Hi.

That's file is to export in pdf the table.
Did you try to start a room? And record a meeting? Just to try out if all tables work.

**Comment by danionescu2007** [comment]
Actually I did. The counters are displayed, like 1 meeting or 1 recording, as depicted in the first screenshot, but not the table rows. I took a look at the code and the 3 tables, corresponding for meetings, active meetings and recordings, have defined a class named display. I replaced the class in the php file of the module with status, like in the table for security access and I can see the table for created meetings by the plugin and I can join the meeting and so on. But I still cannot see the active meetings or recordings.
I also tried the plugin with different themes, my thought being that could be a conflicting css.
IMHO the class name **display** is not a good choice as it could be most probably conflicting with another css from other module or even from a theme.
Please let me know your thoughts.
Thank you.

**Comment by albertosgz** [comment]
The plugin is based on original bigbluebutton plugin. In fact, the CSS is the same.
Sure, "display" is not the best name, because it is too common, easy to conflict.
Can you make a PR with changes in CSS?

**Comment by danionescu2007** [comment]
I would do it, if I knew how. Can you please walk me through it with some steps to perform? Do I have to make a fork or something?
Thank you.

**Comment by albertosgz** [comment]
I am really sorry, I was really busy this period.
Thank you so much @danionescu2007 to fix the issue!

**Comment by albertosgz** [comment]
Fixed on version 1.1.21:
https://wordpress.org/plugins/bbb-administration-panel/#developers
https://github.com/albertosgz/Wordpress_BigBlueButton_plugin/commit/ab2a2cdc3daa083ce4a1313158e5aac79f5cd4bc
Thank you so much dear!
