### ISSUE TITLE
auto-join room when 'wait for moderator' is active does not work

### ISSUE THREAD

**Issue by danionescu2007** [albertosgz/Wordpress_BigBlueButton_plugin#29]
![image](https://user-images.githubusercontent.com/4688610/89707238-fb134800-d974-11ea-9709-50633726b0c0.png)

I may have hit a bug here or maybe something changed on the BBB API side.
There is an update for BBB since a couple of days ago.
Please let me know what other information do you need for debug.
Thank you.

[EDIT]
Further in the console I get repeated errors: json parse error

**Comment by albertosgz** [comment]
I know someone which happened the same, but I couldn't find the root of the issue. Can you dig into it a little bit more?
About the errors 400 and json error, I don't know what is causing it.

**Comment by danionescu2007** [comment]
I am still digging into it. I will keep you posted.

**Comment by albertosgz** [comment]
To me it looks great!!! Than you so much again!!!
Please don't hesitate to make Pull Requests for these fixes.

**Comment by albertosgz** [comment]
Fixed on version 1.1.21:
https://wordpress.org/plugins/bbb-administration-panel/#developers
https://github.com/albertosgz/Wordpress_BigBlueButton_plugin/commit/ab2a2cdc3daa083ce4a1313158e5aac79f5cd4bc
Thank you so much dear!
