### ISSUE TITLE
Issue, when Plugin "BBB Administration Panel" is installed in an Wordpress on an Yunohost Server.

### ISSUE THREAD

**Issue by akhfrorath** [albertosgz/Wordpress_BigBlueButton_plugin#30]
Your Plugin "BBB Administration Panel" is funcion fine in my Wordpress 5.5.1 which is installed in a normal Webhosting packet.
When I install it in Wordpres 5.5.1 on an virtual hostet [Yunohost Server,](https://yunohost.org/) it does not function with the URL and shared secret data of my own BigBlueButton Server. Otherwise when I use the URL and the shared secret from the blindsite testserver it is function OK.
Have someone an idea for resolve?

**Comment by albertosgz** [comment]
If it works with the URL and secret from blindsite. it means the plugin is installed ok. I don't know what is happening. Sorry.
