### ISSUE TITLE
Reimplement Post type support

### ISSUE THREAD

**Issue by Mte90** [albertosgz/Wordpress_BigBlueButton_plugin#31]
I prefer to use this plugin but the original one use the post type to create events.  
In that way for us is more simple to let our users to create rooms and so on without access to BBB.

**Comment by albertosgz** [comment]
Hi. Can you explain more about the post event creation? Because I don't remember such feature. Cna you send to me some screenshot or explanation of it?

**Comment by Mte90** [comment]
Yes of course, the original plugin has a room post type.

So create also the frontend automatically for the event/meeting so I don't need to use another post type and if we want more users to use it in this way is more simple.

![Screenshot_2020-11-20 Rooms ‹ Eventi ILS — WordPress](https://user-images.githubusercontent.com/403283/99811696-cbfc9d00-2b45-11eb-8f53-52610b6acdc3.png)

Instead in your plugin to do that I have just the settings panel of the plugin inside settings.

**Comment by albertosgz** [comment]
The screenshot looks like the new version of the BigBlueButton plugin from BlindSoftware. But my plugin is based on its first version, so is totally different. If you need such feature, I what are you expecting and how to do it. Regards.
