### ISSUE TITLE
Wordpress shortcode

### ISSUE THREAD

**Issue by feragnoli** [albertosgz/Wordpress_BigBlueButton_plugin#32]
Is there a complete list of arguments for wordpress shortcode?
Ther isn't one on the bigbluebutton plugin page. The 'submit' argument does not seem to be interpreted correctly by wordpress (in gutenberg) either.
thank you

**Comment by albertosgz** [comment]
Hi @feragnoli 

It should be in the readme of this project. If it is not so exhaustive, you need to dig into the code, sorry.
The submit button should work in Gutenberg also. I test it. Can you provide more info about. 

Thanks!
