### ISSUE TITLE
getMeetingInfoURLWithoutModeratorPwUrl method missing in the BigBlueButtonAPI

### ISSUE THREAD

**Issue by anton5rov** [albertosgz/Wordpress_BigBlueButton_plugin#33]
Hi, Alberto,
Clicking in the row in the "List of Active Meeting Rooms in BBB Server" section in the admin panel doesn't work as expected for me. The text stated: "Click on the row to see the participants list", but I receive an error in the console "500 (Internal Server Error)". I guess it's a bug due to calling to a non-existing method. The function bbbadminpanel_action_get_meeting_info() at row 1586 calls BigBlueButtonAPI::getMeetingInfoURLWithoutModeratorPwUrl($meetingID, $url_val, $salt_val) but such a method is not defined in the BigBlueButtonAPI.
![image](https://user-images.githubusercontent.com/3611832/109394058-b1e50e80-792d-11eb-8697-3b033cbb04f2.png)

I think I can add the method myself, but I'm afraid it could be missing again in the next update.

**Comment by albertosgz** [comment]
Thank you for the review. Can you make a pull request with the change? it would be very helpful for many people.

**Comment by anton5rov** [comment]
Pull request send from **antonp** branch. Some comments added in the code, I hope it wouldn't be a problem to remove them before merge if unnecessary.

**Comment by albertosgz** [comment]
Already merged. I will update the plugin asap!

**Comment by albertosgz** [comment]
Plugin updated! please, let me know how it goes.

Alberto Sánchez González

**Comment by anton5rov** [comment]
Checked, participants list shows ok now.
