### ISSUE TITLE
Wordpress Critical issues version 5.6.2

### ISSUE THREAD

**Issue by JT1983** [albertosgz/Wordpress_BigBlueButton_plugin#35]
Hello,

These 3 critical errors are showing when the BBB Admin app is activated. 

![wordpress critical](https://user-images.githubusercontent.com/79865502/109537705-1da6b300-7ab7-11eb-9f08-c3ded7c74fd0.png)

**Comment by albertosgz** [comment]
Hi.

I never see that errors in any of my installations and activations. Can you share the procedure you follow, the wp version and the plugins you have installed before?

It looks is claiming for another reason, not just this plugin.

**Comment by JT1983** [comment]
Hello the wordpress version is 5.6.2.

I went through the process of disabling the plugins one at a time to see what generated the above critical issues. When I disabled the bbb admin plugin all errors resolved. 

Here is a list of the plugins we are using on the site.

Plugin | Details
-- | --
Amelia | Version: 3.0.2Path: https://wpamelia.com/
CartFlows | Version: 1.6.8Path: https://cartflows.com/
Child Theme Configurator | Version: 2.5.8Path: http://www.childthemeconfigurator.com
Contact Form 7 | Version: 5.4Path: https://contactform7.com/
Design Upgrade for LearnDash | Version: 2.8.2Path:
Elementor | Version: 3.1.1Path: https://elementor.com/?utm_source=wp-plugins&utm_campaign=plugin-uri&utm_medium=wp-dash
Facebook for WooCommerce | Version: 2.3.1Path: https://github.com/facebookincubator/facebook-for-woocommerce/
FluentSMTP | Version: 1.0.1Path: https://fluentsmtp.com
Frontend Reset Password | Version: 1.2Path:
Google Ads & Marketing by Kliken | Version: 1.0.7Path: https://woo.kliken.com/
LearnDash LMS | Version: 3.3.0.3Path: http://www.learndash.com
LearnDash LMS - Course Grid | Version: 1.7.0Path: http://www.learndash.com
LearnDash LMS - WooCommerce Integration | Version: 1.9.1Path: http://www.learndash.com/work/woocommerce/
LearnDash Private Message | Version: 1.0.0Path: immerseus.com/
LearnDash ProPanel | Version: 2.1.4Path: http://www.learndash.com
Limit Login Attempts Reloaded | Version: 2.19.2Path:
LoginPress - Customizing the WordPress Login | Version: 1.5.0Path: https://WPBrigade.com/wordpress/plugins/loginpress/
Nav Menu Roles | Version: 2.0.0Path: http://www.kathyisawesome.com/449/nav-menu-roles/
Peter's Login Redirect | Version: 2.9.7Path: http://www.theblog.ca/wplogin-redirect
Simple Local Avatars | Version: 2.2.0Path: https://10up.com/plugins/simple-local-avatars-wordpress/
Starter Templates | Version: 2.6.1Path: https://wpastra.com/
Student Parent Access for LearnDash | Version: 2.0.0Path: immerseus.com
Uncanny Toolkit for LearnDash | Version: 3.4.2Path: https://www.uncannyowl.com/uncanny-learndash-toolkit/
User Role Editor | Version: 4.58.3Path: https://www.role-editor.com
Visibility Control for LearnDash | Version: 1.4Path: https://www.nextsoftwaresolutions.com/learndash-visibility-control
WooCommerce | Version: 5.0.0Path: https://woocommerce.com/
WooCommerce Cart Abandonment Recovery | Version: 1.2.10Path: https://cartflows.com/
WooCommerce Stripe Gateway | Version: 4.9.0Path: https://wordpress.org/plugins/woocommerce-gateway-stripe/
WPForms Lite | Version: 1.6.5Path: https://wpforms.com
Yoast Duplicate Post | Version: 4.1.1Path: https://yoast.com/wordpress/plugins/duplicate-post/
Yoast SEO | Version: 15.9Path: https://yoa.st/1uj

Thanks

**Comment by albertosgz** [comment]
I will take a look what can it be causing that and fix it.

Thanks!

**Comment by JT1983** [comment]
Thank you. Really appreciate your work. It's a great plugin.

**Comment by albertosgz** [comment]
I just updated the plugin to the version 1.1.20. One of the improvements is
the removing of `session_start()`, which was unnecessary for the plugin
purpose. Can you try it out and let me know?
The other two issues are not related with the plugin I guess, but with the
speed of the BBB connection.

Alberto Sánchez González

**Comment by JT1983** [comment]
Hi Alberto,
I have installed the plugin and it has fixed the errors I was receiving. I will do a full test of everything over the next few days and let you know if anything comes up.

Thanks for all you do. You are a star.
Joel

**Comment by albertosgz** [comment]
I guess is working fine. Closing thread due to inactivity.
