### ISSUE TITLE
The token: 608e552182db4694bc7f544eed92f993 is not associated with an existing room.

### ISSUE THREAD

**Issue by lrit18** [albertosgz/Wordpress_BigBlueButton_plugin#37]
Hello,
i like to insert a created room with token 608e552182db4694bc7f544eed92f993 in my page.
so i entered the shortcode [bigbluebutton token=608e5521-82db-4694-bc7f-544eed92f993]
But on my page I recieve the following error message:
The token: 608e552182db4694bc7f544eed92f993 is not associated with an existing room.

When I try to create a room I get the message "Unable to display the meeting. Please check the url of bbb server AND check to see if the bbb server is running."

the room will be created in the future and I can also join it using the button in the backend. it runs on my server.

What do I wrong?
thanks

**Comment by lrit18** [comment]
I close this issue: I also installed and activated the official bbb plugin. I have now deactivated this. now everything works.

**Comment by albertosgz** [comment]
Hi. Was the room created with the plugin? Regards.

Alberto Sánchez González

**Comment by lrit18** [comment]
Hi Alberto,
yes, I created the rooms with your plugin.
Thanks

**Comment by albertosgz** [comment]
I'm really sorry about that. Can you share an screenshot of the
configuration of the room?

**Comment by lrit18** [comment]
What kind of screenshot do you need exactly? In the end it worked. To do this I had to uninstall the official BBB plugin from Wordpress.

**Comment by albertosgz** [comment]
If it works, no need to send any pictures. I meant one about the
configuration, but no need anymore, since it works.

I am glad it finally works. Regards.

Alberto Sánchez González

**Comment by lrit18** [comment]
all right, thank you for your willingness to support me!
