### ISSUE TITLE
CSV bulk upload to create rooms

### ISSUE THREAD

**Issue by lrit18** [albertosgz/Wordpress_BigBlueButton_plugin#38]
Hello everybody,
I have to create around 50 rooms.
Fortunately, there is the function to upload a CSV file with the room details.
I filled out the template and then uploaded it. After I click on "Import" the page loads. But then nothing more happens. 
No rooms were imported. Where is the mistake?

My CSV file looks like this:

Meeting Room Name;Meeting Token;Attendee Password;Moderator Password;Wait for Moderator;Recorded;VoiceBridge;Welcome Message;Join Custom Parameters
john doe;;afr;sprechtag-ks;no;no;11111;Welcome to John;

Thanks for help

**Comment by albertosgz** [comment]
Hi!

I am using this [call](https://www.php.net/manual/es/function.fgetcsv.php) to read CSV files, and what I see in the [code](https://github.com/albertosgz/Wordpress_BigBlueButton_plugin/blob/01af9b09e7ffc44e84686a10c027d2ded6beabba/bigbluebutton-plugin.php#L1126), is using the delimiters by default ",". 

Can try out with them?

**Comment by lrit18** [comment]
Hi,
thanks for your answer.
I thought this was the key point. But nothing changes when I try ",".
Does the first line have to be included in the file?
Do "" have to be set?
Is it not necessary for me to provide the Meeting Token?

My content in csv file:
"Meeting Room Name", "Meeting Token", "Attendee Password", "Moderator Password", "Wait for Moderator", Recorded, VoiceBridge, "Welcome Message", "Join Custom Parameters"
"Room name" ,, "password", "password-ik", no, no, 11111, "Welcome to my meeting",

Thanks

**Comment by albertosgz** [comment]
Can you try to setup "" to all of the columns? Just in case.

**Comment by lrit18** [comment]
Done. But nothing else happens:
![csv](https://user-images.githubusercontent.com/20736613/115865015-055c7000-a438-11eb-960c-513d85f9ca85.JPG)

**Comment by albertosgz** [comment]
Could it be a because a wrong encoding or the BOM char?

**Comment by lrit18** [comment]
I downloaded the template file from plugin page in my WordPress. It is UTF8 without BOM. Also UTF-8 BOM is possible. I opened with Notepad++
See my file attached.
[backup_template.zip](https://github.com/albertosgz/Wordpress_BigBlueButton_plugin/files/6366033/backup_template.zip)

**Comment by lrit18** [comment]
Did you do magic? Suddenly, without doing anything, the plugin page now looks better :) the csv upload also seems to work now.

**Comment by albertosgz** [comment]
No, I didn't do anything at all. What is the issue? what is _handling modus_?

**Comment by lrit18** [comment]
Please see screenshot attached.
![bbb](https://user-images.githubusercontent.com/20736613/115949504-ef9d8800-a4d5-11eb-906c-3fb99b54656c.JPG)
The CSV upload now only works if you have activated the problem handling mode. Then the errors in console from #39  disappear.

**Comment by albertosgz** [comment]
Is that "problem handling mode" a plugin or ships by default with WP?

Alberto Sánchez González

**Comment by lrit18** [comment]
It is a default functionality in WordPress.

**Comment by albertosgz** [comment]
I need more time to dig into it. It looks like the plugin needs to be
updated according last WP version. But at the moment I am very busy. I hope
to find room to do it soon.

Alberto Sánchez González

**Comment by lrit18** [comment]
Exactly, that's what I'm assuming too. There was a big jQuery update on WordPress. Here is some more information for analysis purposes:

2021-04-25 07:31:11 | jQuery.fn.load() is deprecated | Plugin: BigBlueButton | http://xxx/wordpress-dev/wp-content/plugins/bigbluebutton/admin/js/bigbluebutton-admin.js 

I can understand that it means a lot of effort. Respect to you for the plugin and thank you for your support. I look forward to an update soon.

**Comment by albertosgz** [comment]
Hi @lrit18 , I just test it myself with a fresh installation of WP 5.8.3, and I don't such error on console.
Is still happening?

**Comment by albertosgz** [comment]
Close due to inactivity. In case the error comes up again, please open a new issue. Thanks!
