### ISSUE TITLE
The recordings deleted are still in the table

### ISSUE THREAD

**Issue by albertosgz** [albertosgz/Wordpress_BigBlueButton_plugin#5]
in the recording list table, after deleted a recording, the row is still in the table

**Comment by albertosgz** [comment]
it looks like an issue in the code of the plugin, since I can't find the recording in /var/bigbluebutton/recording/raw folder according the date

**Comment by albertosgz** [comment]
I see what's happening.

According the source file, we are requesting for the recordings of the current rooms configured with **any state**, [file bbb_api.php, line 223](https://github.com/albertosgz/Wordpress_BigBlueButton_plugin/blob/master/php/bbb_api.php#L223).

The description of the API of BBB is clear, according the definition of the call [getRecordings](http://docs.bigbluebutton.org/dev/api.html#getrecordings). We are getting all recordings of the rooms set by the plugin, regardless their state, for example if they were deleted.

This call is only used to display the table of recordings.

So the point is, what expected behavior should it be?
Do we want to display the recordings of all rooms? or only the rooms set in each WP instance?
Do we want to display all of the recordings? or only the published or unpublished? 
Do we have to add a column with the state of the recording?

**Comment by paulbelcher2** [comment]
- Remove "deleted" rooms from recodings display.  This rule should go for ALL states but deleted.
- Add a column to display all other state, but deleted, ie. Processing, Complete, etc.
